pipeline {
    agent none
    
    parameters {
        string defaultValue: 'main', name: 'BRANCH', trim: true
    }

    environment {
        BRANCH_NAME = "${BRANCH}"
    }

    stages{
        stage('BUILD') {
            agent { label: 'slave1' }
            steps{
                 sh '''
                    sleep 5
                    echo "This is a BUILD stage $BRANCH_NAME"
                '''
            }
        }

        stage('TEST') {
            agent { label: 'slave2' }
            steps {
                sh '''
                    sleep 6
                    echo "This is a TEST stage $BRANCH_NAME"
                '''
            }
        }

        stage('DEPLOY') {
            steps{
                agent { label: 'master' }
                sh '''
                    sleep 5
                    echo "This is a DEPLOY stage $BRANCH_NAME"
                '''
            }
        }
    }
}

